parameters:
    jms_serializer.entity_object_constructor.class: PQstudio\RestUtilityBundle\Construction\EntityObjectConstructor
    jms_serializer.doctrine_object_constructor.class: JMS\Serializer\Construction\DoctrineObjectConstructor
    pq.rest.controller.class: PQstudio\RestUtilityBundle\Controller\PQRestController
    pq.acl.class: PQstudio\RestUtilityBundle\Acl\Acl

services:
    jms_serializer.entity_object_constructor:
        class: %jms_serializer.entity_object_constructor.class%

    jms_serializer.doctrine_object_constructor:
        class: %jms_serializer.doctrine_object_constructor.class%
        arguments: [@doctrine, @jms_serializer.entity_object_constructor]
    jms_serializer.object_constructor:
            alias: jms_serializer.doctrine_object_constructor
    utility.response_metadata:
        class: PQstudio\RestUtilityBundle\Utility\ResponseMetadata
    kernel.listener.exception_listener:
        class: PQstudio\RestUtilityBundle\EventListener\ExceptionListener
        arguments: [@jms_serializer]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    pq.acl:
        class: %pq.acl.class%
        arguments: [@security.acl.provider]
